### ISSUE TITLE
Documentation: Unable to hold after completing an initial hold/resume

### ISSUE THREAD

**Issue by L1kMakes** [L1kMakes/sipml5-ng#1]
Creating this issue as documentation in our repository of what is an upstream issue.

If you make an audio call, you can place it on hold, then resume it.  Afterwards, if you try to put the call on hold again, it does NOT go on hold and the hold button grays out.

The expected result is that you should be able to hold/resume as many times as you want in a call.

We discovered this when implementing features for multi-call switching.  Worried that our modifications to the sipml5 api caused this so we reverted to the upstream doubango api js and experienced the issue as well, then we fully implemented doubango's reference UI and api and again experienced the issue.

We have submitted upstream bugs to the 3 parent repositories (one of which has issues disabled, so I emailed the dev:

- https://github.com/DoubangoTelecom/sipml5/issues/360
- https://github.com/cloudonix/sipml5-ng/issues/4

We are also attempting to fix this ourselves, however the nuance of the sip api is slightly outside our expertise.

**Comment by surfrock66** [comment]
This was solved in the previous commit https://github.com/L1kMakes/sipml5-ng/commit/6fd731d57e79fb2e07e2fc84f216a1d4fd63ef21
